### ISSUE TITLE
protocol fails if the parameter 'save unweighted micrographs' to be set 'No'

### ISSUE THREAD

**Issue by mohsenkazemi** [scipion-em/scipion-em-motioncorr#25] opened 2019-11-12 00:04 UTC
if this parameter be set to 'No' in the last step, with error '...no outputMicrographs...' protocol fails.
Setting this parameter to 'Yes', protocol works normal.

**Comment by azazellochg** [comment] 2019-11-23 14:24
Duplicate of https://github.com/I2PC/scipion/issues/2053

**Closed by azazellochg** 2019-11-23 14:24 UTC
